### ISSUE TITLE
Improve UI/UX of the patient waiting room screen 

### ISSUE THREAD

**Issue by pedropiccaro** [rodrigogs/barracao-digital#44]
it is necessary to make it clear that the patient will receive contact through the waiting room

**Comment by kuroski** [comment]
> As a Patient, I want to know where the doctor will contact me after I register.

We have some problems with the layout of our current "Patient waiting room" screen.

The screen is not intuitive enough, so patients that register in the system just grab the generated ticket number e close the browser, because they think the doctor will approach through WhatsApp or E-mail.

We need to make the screen more intuitive and make it more "obvious" that the contact will be made IN the waiting room screen.

![image](https://user-images.githubusercontent.com/1855125/80142653-d8b71380-85ab-11ea-99d9-b4187d642fc2.png)

In this issue I'll try to suggest some other layouts, and we can vote if its good or not =D

**Comment by kuroski** [comment]
@pedropiccaro What do you think?

![gif](https://thumbs.gfycat.com/WeirdPlasticFairybluebird-size_restricted.gif)

![localhost_3000_patient_323803173(iPad)](https://user-images.githubusercontent.com/1855125/80241711-5c343b80-8664-11ea-9420-a022cfcc5b85.png)

**Comment by pedropiccaro** [comment]
Ficou ótimo!
