### ISSUE TITLE
Enviar vs Enviar e continuar

### ISSUE THREAD

**Issue by laurasstephan** [rodrigogs/barracao-digital#53]
On the Step 2 of the appointment (doctor view) - Em Andamento - I write the instructions for the patient and there are two options: **Enviar** or **Enviar e continuar**. If I send a message by clicking on **Enviar**, and then proceed to the Step 3 (Finalizar) by clicking on the Step name instead of clicking on **Enviar e continuar**, the message that I write on Finalizar is not sent.

**Comment by kuroski** [comment]
I couldn't reproduce the problem =(.
Did I follow the correct steps?
- Open the patient status modal
- Go to the step `Em Andamento`
- Describe something and click um the `Enviar` option
- Click in the `Finalizar` step directly instead of clicking in the `Enviar e continuar` button
- Describe the ending message
- Submit

![gif](https://thumbs.gfycat.com/ImpartialDetailedAmericanratsnake-size_restricted.gif)

**Comment by laurasstephan** [comment]
Yes! From the doctors point of view everything works fine. But did you check the patients screen? They do not receive the ending message in this case (at least in my tests). 

Laura Stephan

**Comment by laurasstephan** [comment]
I ran the same tests again this morning with the same devices and it’s all working fine, no worries. Case closed!
