### ISSUE TITLE
Superposition of fields on the patient screen

### ISSUE THREAD

**Issue by laurasstephan** [rodrigogs/barracao-digital#56]
This is on Chrome for iOS.

![IMG_7704](https://user-images.githubusercontent.com/63982998/80039853-e7baa900-854c-11ea-914c-1443c2ba36a1.PNG)

**Comment by laurasstephan** [comment]
just tested on Chrome for Android and it is all good.

**Comment by laurasstephan** [comment]
The browser where the bug happens is Chrome version 80.0.3987.95
iOS 12.4.5 
iPhone 6

**Comment by kuroski** [comment]
Hello @laurasstephan 
I already fixed that in the commit: 4ee243a08d27df34d6b252622ff08114328b4ecc

Here is a screen shot from my iPhone using Chrome in https://web.barracaodigital.com

![IMG_38D08A739C58-1](https://user-images.githubusercontent.com/1855125/80132620-40656280-859c-11ea-9035-1d903fd9e28a.jpeg)

Could you check it if this issue is ok?

Don't forget to refresh the browser, and maybe clear the cache (browser data) because your browser can still be displaying an old version of the website.

If the problem is still there, I will investigate more 😄

**Comment by laurasstephan** [comment]
All working good now :D
